# Site settings
title: Tupperware Sternkopf
email: kerstin_sternkopf@web.de
url: https://example.github.io
description: "Tupperware Kreis Schwarzenberg"
keywords: "your keywords, separated by commas"
skills: "Erzgebirgskreis: zum Beispiel Schwarzenberg, Aue, Annaberg, Schneeberg, Oberwiesental"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: stefantaubert

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e61a87 #helllila
  primary-rgb: "38,38,238" #blau
  secondary: b8156c #lila
  secondary-dark: 0a9b9f #dunkellila
#   primary: 2fed26 #grün
#   primary-rgb: "38,38,238" #blau
#   secondary: 0a9b9f #türkis
#   secondary-dark: b8156c #lila

# Footer settings
footer:
  copyright: Kerstin Sternkopf
  location: Standort
  social: Netzwerke
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/kerstin.sternkopf.73

# Postal address (add as many lines as necessary)
address:
  - line: Schwarzenberg
  - line: Sachsen

# Credits content
credits: 'Freelancer ist kostenlos und ein Open Source Projekt von <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
