# Site settings
title: Tupperware Sternkopf
email: your-email@domain.com
url: https://example.github.io
description: "Tupperware Kreis Schwarzenberg"
keywords: "your keywords, separated by commas"
skills: "Erzgebirge - Schwarzenberg - Pöhla - Grünstädtel - Aue"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: stefantaubert

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d0187a #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: d0187a #FD6E8A
  secondary-dark: 0a9b9f #A2122F

# Footer settings
footer:
  copyright: Kerstin Sternkopf
  location: Standort
  social: Netzwerke
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/kerstin.sternkopf.73

# Postal address (add as many lines as necessary)
address:
  - line: Grünstädtel
  - line: Schwarzenberg, Sachsen

# Credits content
credits: 'Freelancer ist kostenlos benutzbar und ein Open Source Projekt von <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
